var CONFV8=[
	"SUQxMDMzMzooMTQsMTIpOigyLDEwKTooOCw4KTooMCwyKTooMTMsMCk6KDksMCk6KDUsMCk6MQ==",
];
var CONFV8R=[
	"SUQxMDMzMzooMTQsMTIpOigyLDEwKTooOCw4KTooMCwyKTooMTMsMCk6KDksMCk6KDUsMCk6MQ==",
];
